### ISSUE TITLE
Errors in make DEBUG

### ISSUE THREAD

**Issue by deciphyre** [chardmeier/docent#2]
/usr/bin/ld: CMakeFiles/detailed-docent.dir/src/detailed-docent.cpp.o: undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: **\* [detailed-docent] Error 1
make[1]: **\* [CMakeFiles/detailed-docent.dir/all] Error 2
make: **\* [all] Error 2

**Comment by chardmeier** [comment]
Can be worked around by adding -lpthread to the list of libraries linked into Docent, in the set clause starting at line 210 in CMakeLists.txt:

set(DECODER_LIBRARIES
        decoder
        stemmer
        ${Arabica_LIBRARIES}
        ${MOSES_LIBRARIES}
        ${Boost_LIBRARIES}
        ${TCMALLOC_LIBRARIES}
        -lpthread)

I'm not currently adding this to the master branch because I'm not completely sure it won't break somebody else's build.
